### ISSUE TITLE
Implement A Function To Resolve A Question (Back-End) - User Story 5

### ISSUE THREAD

**Issue by Maria-Aidarus** [CMU-17313Q/fall23-nodebb-just-relax#17]
Estimated effort for each task: This would be moderatley difficult as you need change the back end code for a question to be counted resolved.
Dependencies: Dependent on #16, there needs to be a button for users to push for the action to happen.
Acceptance criteria: When you can successfully resolve your question when someone answers it, and it appears to others as resolved.

**Comment by hjoad** [comment]
I was not able to finish this issue by sprint 1 because I couldn't figure out how to connect the button to the route to process the click in the back-end. I have all the functions that I believe are necessary. I also have the timeout error which prevents me from properly testing. The files I changed are:
- /src/api/posts.js - wrote API function to resolve posts - 5 lines of code
- /src/controllers/write/posts.js - made a function to mark posts as resolved - 8 lines of code
- /src/posts/create.js - added resolve const - 2 lines of code
- /src/posts/data.js - added field for resolved - 1 line of code
- /src/posts/index.js - require the new file for resolving - 1 line of code
- /src/posts/resolved.js - new file with basic resolve functions - 48 lines of code
- /src/routes/write/posts.js - set up API route - 3 lines of code

total: 7 files changed, 68 lines of code
